### ISSUE TITLE
Add Vagrant support (and docker)

### ISSUE THREAD

**Issue by rllola** [BitcoinAmiens/dogecoin-tipping-bot#19]
Add Vagrant with a regtest dogecoin node for local development.

**Comment by mbaumanndev** [comment]
Is it possible to do that with Docker rather than Vagrant ?
Since we have a Dockerfile in the repo for the bot itself, i think it would be a good things to reuse Docker here instead of adding more virtualization technologies

**Comment by rllola** [comment]
Vagrant support Docker out of the box and would allow us to start a local node for development with all the proper configuration with one command. It would still be possible to create a local node using the docker-dogecoin (https://github.com/BitcoinAmiens/docker-dogecoin) but it is asking a little more steps to get it started. Also you don't want to add it this to the repo as it is only needed for dev purpose. 

Another advantage of a virtualbox is to develop using the same tool (node and npm version) and be sure to not mess with your local configuration and keep everything in one place that you can delete and start easily.

**Comment by rllola** [comment]
After thinking about it, using vagrant could be a bit messy. Adding a small script that would start a docker container running dogecoind in regtest mode could be more lightweight.

Both can still be implemented so dev can use whatever tool fit the best.
