### ISSUE TITLE
Possible to edit to use a different coin?

### ISSUE THREAD

**Issue by StamatisP** [BitcoinAmiens/dogecoin-tipping-bot#28]
I'm going through the files and it seems like replacing the coin used is pretty difficult, is this dogecoin only?

**Comment by rllola** [comment]
Hi @Kevin43,

Yes, it is dogecoin only. What coin would you like to use ?

**Comment by StamatisP** [comment]
Trying to edit it to support that new Garlicoin that recently came out, so I figured I should try my hand at this.

**Comment by rllola** [comment]
Good luck with it. I am closing this issue.
