### ISSUE TITLE
User can tip himself

### ISSUE THREAD

**Issue by mbaumanndev** [BitcoinAmiens/dogecoin-tipping-bot#31]
Using the `/wow tip` command, a user can tip itself.
The amount of doge he owns doesn't change, but I think the normal behaviour would be to throw an error

**Comment by rllola** [comment]
See PR https://github.com/BitcoinAmiens/dogecoin-tipping-bot/pull/38

**Comment by rllola** [comment]
See PR https://github.com/BitcoinAmiens/dogecoin-tipping-bot/pull/38
