### ISSUE TITLE
Menu and Start command

### ISSUE THREAD

**Issue by west-pool** [BitcoinAmiens/dogecoin-tipping-bot#34]
Hi all,

we have some questions:
to start the bot normally is with npm run dev or is another command ?
Regarding the commands, /wow works but the other dont like /help and so.
What I'm doing wrong ?

thank You,

Luis

**Comment by mbaumanndev** [comment]
You have to call the commands with the following pattern "/wow [command] [args]"
For starting the bot, i have to check that, i don't remember

**Comment by west-pool** [comment]
Got it,

/wow works, but i will change.
I think to start normaly is npm start right?

Luis

**Comment by rllola** [comment]
Hi Luis,

Yes to start normally the bot it is `npm start`.
