### ISSUE TITLE
Health check and auto-restart when crashed

### ISSUE THREAD

**Issue by mbaumanndev** [BitcoinAmiens/dogecoin-tipping-bot#37]
I think we could add an health check on the bot, in order to restart it or restart the dogecoin node when something crash

**Comment by dragonhuntr** [comment]
You could always use npm forever, incase the bot crashes.

**Comment by rllola** [comment]
Npm forever is a good solution. We are also using docker so we can use docker restart too. And if we want something to check ing we can do use this https://healthchecks.io/

Pick your solution.

**Comment by rllola** [comment]
If running in docker we can use `docker run --restart=unless-stopped ...`
