### ISSUE TITLE
Add withdraw command

### ISSUE THREAD

**Issue by rllola** [BitcoinAmiens/dogecoin-tipping-bot#6]
Add a withdraw command to move fund to an external address.

Command example : 
```
/wow withdraw <amount> <dogecoin_address>
```

**Comment by mbaumanndev** [comment]
I can do it this week, it could be intresting to deal with RPC since i dind't had the opportunity to do it until now. If you're ok with this, can you assign me this issue ?

**Comment by rllola** [comment]
@Petrucheqa Already started to work on this last night.
